### ISSUE TITLE
Booking module | List Booking Feature

### ISSUE THREAD

**Issue by Naveena-007** [fssa-batch3/sec_a_naveenasri.nagarajan__corejava_project_2#18]
### User Story
As a user looking to book a design, I want to have a streamlined process for browsing and selecting designs to book. This process should allow me to view available designs, select a design to book, provide booking details, and confirm the booking.

### Task: Implement Design Booking for Users
- [ ] Develop the Data Access Object (DAO) Layer for booking designs.
- [ ]  Implement the Service Layer to handle the design booking process for users.
- [ ] Create JUnit Test Cases to ensure the correctness of the design booking functionality
- [ ] Verify that all test cases are passing successfully.
- [ ] Enhance code clarity by adding clear and concise comments to explain intricate logic.

### DAO:
- [ ] listBookingsByArchitectId()
- [ ] listBookingsByUserId()

### Service:
- [ ] listBookingsByArchitectId()
- [ ] listBookingsByUserId()

### Test:
- [ ] testListBookingsByArchitectIdNotEmptyTrue()
- [ ] testListBookingsByArchitectIdWithNoBookings()
- [ ] testListBookingsByUserIdNotEmptyTrue()
- [ ] testListBookingsByUserIdWithNoBookings

### Estimation 
- [ ] 6 hours

## Flow
``` mermaid 
graph TD
A[[Start]] -->|Architect Initiates Design Listing| B([Fetch Designs])
B -->|Designs Found| C([Display Design List])
B -->|No Designs Found| D{{No Designs Available}}
C --> H[[End]]
D --> H
```
